services:
  account-service:
    build: .
    container_name: account-service
    ports:
      - "4000:4000"
    restart: always
    networks:
      - gateway_app-net

networks:
  gateway_app-net:
    external: true
